### ISSUE TITLE
A script to parse usernames from a classroom repo

### ISSUE THREAD

**Issue by dhowe** [dhowe/Miscellaneous#1]
by end of weekend, we need a script to parse all usernames from a classroom repo such as: https://classroom.github.com/classrooms/13428665-introduction-to-media-computing/assignments/imc-assignment-9

**Comment by cqx931** [comment]
Since I didn't find any way to get this info/list of repo from git command, I suppose this need to be done by web scraping?

**Comment by dhowe** [comment]
I've done most of it [here](https://github.com/dhowe/classroom-util/blob/master/fetch-students.sh), via curl, jq and bash

Pull classroom-util, then run:
`$ ./fetch-students.sh` 
OR
`$ ./fetch-students.sh cqx931` 

You will need to add pagination support to get all the repos though (see [this](https://developer.github.com/guides/getting-started/#pagination))

**Comment by cqx931** [comment]
After reading the link you provided I was able to get the Link header from github.
But there are two things that I am not so sure about:
1. The next page link I get from making the request with "type=private" is following: https://api.github.com/organizations/13428665/repos?type=private&page=2

But if I do `curl -i -u cqx931 https://api.github.com/organizations/13428665/repos?type=private&page=2`, I won't be able to get the info but this message `[1] 78040`

However, if I delete the `type=private` part, I can get the next page/last page correctly.

2.The traversing example in this page [here](https://developer.github.com/guides/traversing-with-pagination/) is in ruby. And I tried to parse this with regex in shell, but up to this point I didn't manage to get look around to work in grep... I think I still need to learn more about shell commands.
`Link: <https://api.github.com/organizations/13428665/repos?type=private&page=2>; rel="next", <https://api.github.com/organizations/13428665/repos?type=private&page=7>; rel="last"
`

**Comment by cqx931** [comment]
done
