### ISSUE TITLE
'Writing Digital Media' website

### ISSUE THREAD

**Issue by dhowe** [dhowe/Miscellaneous#11]
- [x] Need to find an app or script that can crawl [the course website](https://rednoise.org/wdm), view each page, and save it all to folder (we can then run it on a schedule)
- [x] Need to check the links on the [resources page](https://rednoise.org/wdm/index.php?n=Main.Resources), and delete any that are dead or outdated
- [x] Need to check the links on the [artists](https://rednoise.org/wdm/index.php?n=Main.Artists) and [works](https://rednoise.org/wdm/index.php?n=Main.Works) pages, and correct any that are missing or wrong (at least try your best)

**Comment by kennyviperhk** [comment]
- for crawling the website(https://rednoise.org/wdm/), how much you need to crawl? anything within rednoise.org? exclude all external links?
- do i edit the website or give u list of deadlinks?

**Comment by dhowe** [comment]
>   for crawling the website(https://rednoise.org/wdm/), how much you need to crawl? anything within rednoise.org? exclude all external links?

The 'wdm' website, which is actually at https://rednoise.org/teaching/wdm, is a wiki (pmwiki to be specific) where pages are dynamically-generated on visit via php. We need to create a static version of this site so that all _pages_ under https://rednoise.org/teaching/wdm are static (external links are fine as are links to other parts of rednoise.org). So we (only) crawl pages under https://rednoise.org/teaching/wdm ...

>   do i edit the website or give u list of deadlinks?

just put results here

**Comment by kennyviperhk** [comment]
- link results has updated in the WebCrawler/ folder.
- the copy of the wdm website is too big (~500MB), i didn't push to to the branch
- inside WebCrawler/ I have put 2 methods in the Readme.txt. Using method#2 for pulling website for now.

**Comment by dhowe** [comment]
>     * link results has updated in the WebCrawler/ folder.
ok  

>     * the copy of the wdm website is too big (~500MB), i didn't push to to the branch
yes, no need to check this into github, the goal is that it runs on a schedule, perhaps once per week

>     * inside WebCrawler/ I have put 2 methods in the Readme.txt. Using method#2 for pulling website for now
ok, but it cannot be scheduled, is that correct?

**Comment by kennyviperhk** [comment]
Method1 can be cause it is using python. But seem missing attachments(pdf) and external links will be broken. 

Method2 is an app so it cant be scheduled, need to download manually with a config file

I cant find other free/open-source method that are better than method 2 yet.

**Comment by kennyviperhk** [comment]
Please check method 3, it works the best and can be scheduled

**Comment by kennyviperhk** [comment]
can be verified and closed as you have another preferred method
