### ISSUE TITLE
'Advertising Positions' website

### ISSUE THREAD

**Issue by dhowe** [dhowe/Miscellaneous#3]
- [ ] description text below
- [ ] other text: credits, title, year, etc.
- [ ] 2-3 images: one male, one female, one detail
- [ ] two images: process (arrows and uv-map)
- [ ] one animation (female, small)

**Comment by dhowe** [comment]
> Advertising Positions, 2017
> Animations / Mixed-media Installation

> These works begin with robots; software robots trained to search the web, according to specific user profiles they have been assigned, including age, gender, location, interests and the like. Each robot is released on the web, driving a modified version of Google’s Chrome browser, to periodically visit sites that it 'likes', and to click links that it selects, which then bring it to new sites. This process continues over several weeks, during which the robot collects, as it has been trained to do, all of the advertisements it is served based on its profile (generally several thousand or more), applying each to a single polygon on the mesh skin of the virtual avatar it inhabits. The training period concludes when the robot’s 3-dimensional figure is complete.
> 
> Special thanks to Sally Chen, Leoson Cheong, and Dorothy Chen for their extensive contributions to this work. Thanks also to Miu Ling Lam, Diane To, Tobias Klein, Tamas Waliczky, and Eddie Leung for their feedback and assistance. 
>

**Comment by cqx931** [comment]
2-3 images: one male, one female, one detail
-The same image as the print? what detail image do you want?(Leoson might need to render one extra image)

**Comment by cqx931** [comment]
one animation (female, small)
-in 720*406px? Do you want the whole animation or a shorter version?

**Comment by dhowe** [comment]
> 2-3 images: one male, one female, one detail
> -The same image as the print? what detail image do you want?(Leoson might need to render one extra image)

A detail from a still of the face, where the ads are very readable and minimal distortion (we should have plenty of pixels for a 72dpi detail, without re-rendering anything)

> 
> one animation (female, small)
> -in 720*406px? Do you want the whole animation or a shorter version?

maybe the whole animation (if the file is not huge)... but doesn't have to be that big -- 400 or 350 x ?

**Comment by cqx931** [comment]
![mockup1](https://cloud.githubusercontent.com/assets/3056154/20917106/82322fc6-bbca-11e6-95a8-00e7a9a738e1.png)
<hr>

![mockup2](https://cloud.githubusercontent.com/assets/3056154/20917107/85672fca-bbca-11e6-8351-9f53f7e6bc00.png)

**Comment by dhowe** [comment]
Looks great for a start... lets check it in (as a subfolder called 'adverpos') here:  https://github.com/dhowe/Website

**Comment by cqx931** [comment]
start: https://github.com/dhowe/Website/pull/13

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/14
As next step, shall I add fancybox for a closer look of the images?
(what you had for [Automatype](http://rednoise.org/~dhowe/automatype/))

**Comment by dhowe** [comment]
yes, please do

**Comment by dhowe** [comment]
closing, refer instead to tickets [here](https://github.com/dhowe/Website/issues)
