### ISSUE TITLE
adnauseam website updates

### ISSUE THREAD

**Issue by dhowe** [dhowe/Miscellaneous#6]
-- update author image (maybe take from website?)
-- add [re:ambiguation article](https://medium.com/@mushon/re-ambiguation-74cda587d609#.w9rnsvwtp) in place of old 'obfuscation workshop' image
-- update images/order/roles

image links: 
         https://avatars1.githubusercontent.com/u/27123?v=3&s=460
         http://90.146.8.18/bilderclient/FE_2007_Identity0230_004_p.jpg

1. Daniel: Co-Creator & Lead Developer
2. Helen: Co-Creator
3. Mushon: Lead Designer

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/655/commits done

**Comment by dhowe** [comment]
Helen's first name is spelled wrong!

Otherwise this looks good, but can we make Helen's head a bit bigger ?

**Comment by cqx931** [comment]
Spelling Error! fixed.
https://github.com/dhowe/AdNauseam/pull/656

**Comment by cqx931** [comment]
https://github.com/dhowe/AdNauseam/pull/657
