### ISSUE TITLE
Full-screen images for AdvertisingPositions on phone [high-priority]

### ISSUE THREAD

**Issue by dhowe** [dhowe/Miscellaneous#9]
At a gallery last night, people wanted to see the adverpos images (nicole, wilson, etc.) and it was impossible to get a full-screen image on anyone's phone (at least on android)

This is quite important. Ideally, a double-tap on any of those images would give a full-screen view

**Comment by cqx931** [comment]
This is the what I see on my iphone. Could you make a screenshot on yours?

**Comment by dhowe** [comment]
on my you see the image fully zoomed, so you can only see one small corner of it.. and you cannot drag it

**Comment by cqx931** [comment]
https://github.com/dhowe/Website/pull/93 Please check.
Now the image should be draggable on Mobile
